### ISSUE TITLE
Starting post-login environment failed (spectrwm)

### ISSUE THREAD

**Issue by point-4ward** [coastalwhite/lemurs#104]
Hi,

Feel like I'm missing something obvious, but after a trying few different combinations I currently have:

/etc/lemurs/wms/spectrwm
```
#!/bin/sh

exec spectrwm
```

Nothing at all in ~/.xinitrc if that makes any difference

When I boot I get the lemurs login prompt with 'spectrwm' at the top, fill in my username and password and it goes to a blank screen.  Log appears to show everything running fine up to `Run X server`, then just says:

```
[lemurs::ui][ERROR] Starting post-login environment failed
```

If I disable the service, reboot, login on tty, put `exec spectrwm` into my ~/.xinitrc and run `startx`, spectrwm loads as expected.

Any ideas please?

**Comment by coastalwhite** [comment]
I am sorry, that was a bit unclear from my side. The script

```
#! /bin/sh
spectrwm 2>&1 > $HOME/lemurs-log
exec spectrwm
```

should create a log file in your home directory `~/lemurs-log`. I am interested in the contents of this file.

**Comment by point-4ward** [comment]
No problem, I did try that combination but nothing was created - let me try it again just to be sure...

Confirmed, nothing is created in the home directory and the output to /var/log/lemurs.log is identical to the one I posted above (except the timestamps, obviously)

I've tried putting `spectrwm 2>&1 > /home/p4/lemurs-log` in case there was some issue with the env var but still nothing 😕

**Comment by coastalwhite** [comment]
Thank you for the continued debugging?

Does the /etc/lemurs/xsetup.sh file exist?

**Comment by point-4ward** [comment]
Hi, sorry for the delay.

Yes, that file is there and is executable - do you need the contents?

**Comment by coastalwhite** [comment]
Mmmh, okay. I have finally to find some time and set up a VM with spectrwm. I do not seem to have any problem. What distribution are you using? It might help to install from the `develop` branch, the debug logging in `/var/log/lemurs` should be vastly improved there.

**Comment by point-4ward** [comment]
This is an Arch install.

I'll have a look over the weekend with the develop branch and get back to you 👍

**Comment by point-4ward** [comment]
Hi,

So I installed from the develop branch today - same problem persists.  Not much has changed in the log though...

```
[INFO  lemurs] Lemurs logger is running
[INFO  lemurs] Switching to tty 2
[INFO  lemurs] UI booted up
[INFO  lemurs::info_caching] Attempting to get a cached information from '/var/cache/lemurs'
[INFO  lemurs::info_caching] Read cache file and found environment 'p4' and username 'None'
[INFO  lemurs::ui] Loading environment 'p4' from cache
[WARN  lemurs::ui::switcher] Failed to find selection with title: 'p4'
[INFO  lemurs::auth] Login attempt for 'p4'
[INFO  lemurs::auth::pam] Started opening session
[INFO  lemurs::auth::pam] Gotten Authenticator
[INFO  lemurs::auth::pam] Got handler
[INFO  lemurs::auth::pam] Validated account
[INFO  lemurs::auth::pam] Opened session
[INFO  lemurs::ui] Setting cached information
[INFO  lemurs::info_caching] Attempting to set cache
[INFO  lemurs::info_caching] Successfully set username in cache file
[INFO  lemurs::post_login::env_variables] Set environment variable 'HOME' to '/home/p4'
[INFO  lemurs::post_login::env_variables] Successfully changed working directory to /home/p4!
[INFO  lemurs::post_login::env_variables] Set environment variable 'SHELL' to '/bin/bash'
[INFO  lemurs::post_login::env_variables] Set environment variable 'USER' to 'p4'
[INFO  lemurs::post_login::env_variables] Set environment variable 'LOGNAME' to 'p4'
[INFO  lemurs::post_login::env_variables] Set environment variable 'PATH' to '/usr/local/sbin:/usr>
[INFO  lemurs::post_login] Set environment variables
[INFO  lemurs::post_login::env_variables] Set environment variable 'XDG_CONFIG_DIR' to '/home/p4/.>
[INFO  lemurs::post_login::env_variables] Set environment variable 'XDG_CACHE_HOME' to '/home/p4/.>
[INFO  lemurs::post_login::env_variables] Set environment variable 'XDG_DATA_HOME' to '/home/p4/.l>
[INFO  lemurs::post_login::env_variables] Set environment variable 'XDG_STATE_HOME' to '/home/p4/.>
[INFO  lemurs::post_login::env_variables] Set environment variable 'XDG_DATA_DIRS' to '/usr/local/>
[INFO  lemurs::post_login::env_variables] Set environment variable 'XDG_CONFIG_DIRS' to '/etc/xdg'
[INFO  lemurs::post_login::env_variables] Set environment variable 'XDG_RUNTIME_DIR' to '/run/user>
[INFO  lemurs::post_login::env_variables] Set environment variable 'XDG_SESSION_DIR' to 'user'
[INFO  lemurs::post_login::env_variables] Set environment variable 'XDG_SESSION_ID' to '1'
[INFO  lemurs::post_login::env_variables] Set environment variable 'XDG_SEAT' to 'seat0'
[INFO  lemurs::post_login::env_variables] Set environment variable 'XDG_VTNR' to '2'
[INFO  lemurs::post_login::env_variables] Set environment variable 'XDG_SESSION_TYPE' to 'x11'
[INFO  lemurs::post_login] Set XDG environment variables
[INFO  lemurs::post_login::x] Start setup of X
[INFO  lemurs::post_login::x] Filling Xauthority file
[INFO  lemurs::post_login::x] Run X server
[ERROR lemurs::post_login::x] Starting X timed out!
[ERROR lemurs::ui] Starting post-login environment failed
```

Only noticable difference for me is the penultimate line "Starting X timed out!" :/

**Comment by coastalwhite** [comment]
Oh, that is very interesting, actually! But unless you have a laptop from 1980s, I would still consider that a bug.

What Lemurs is doing internally is asking X every `100ms` whether it has started. After a set number of tries, it gives up and assumes X is stuck or not starting up at all. Then, it will kill the session and kick you back to the login screen. Not really sure why X is not starting within 20 seconds.

I will leave this issue open as others may have the same problem, but I am not really sure where to go from here. I am attempting to make debugging these problems a lot better, but that is going to take a while.

**Comment by point-4ward** [comment]
No worries - I will wait and see what you come up with.

As I say, using startx after logging in from the tty works fine, it's only through Lemurs.

One thing I had noticed though, is that after I have had a try with Lemurs and then disable it to use startx, I have to delete the .Xauthority file as startx cannot write to it.  I presume this is because Lemurs opens the file when it tries to start X but then it never gets correctly closed as X never starts, but just in case it's another clue for you I thought I'd better include it here.

**Comment by coastalwhite** [comment]
Ah, okay. The `Xauthority` thing was a bug that should be solved on develop. Looking into the rest.

**Comment by 0xDkXy** [comment]
I have the same bug while using awesomewm. But, something weird is that on the another computer which I installed arch before, it worked well. 

And it's seems like it's caused by using systemd. The owner of .Xauthrity is root, so I guess that it will make the timeout of xauth.

**Comment by coastalwhite** [comment]
I have solutions for both problems. Personally, I was blocking the next version for #114 and #115, but it seems like those issues can wait for the next version. I will seek to update Lemurs somewhere in the coming days with fixes for these problems.

**Comment by coastalwhite** [comment]
Good news. I am able to boot into spectrwm on the new version 0.3.1. :smile:
