### ISSUE TITLE
Plasma wayland does not start with XDG_SESSION_ID set

### ISSUE THREAD

**Issue by msmol** [coastalwhite/lemurs#109]
Creating the following file: `/etc/lemurs/wayland/Plasma` 

```
#!/bin/bash

exec startplasma-wayland
```

Plasma fails to start from lemurs unless I rebuild with the following line removed: https://github.com/coastalwhite/lemurs/blob/main/src/post_login/env_variables.rs#L42

**Comment by coastalwhite** [comment]
Hey, thank you for reporting this issue. This is something that was mentioned in #108 as well and is a real issue. Interesting to see that it also effect KDE Plasma Wayland.

I am a bit hesitant to address this issue without some extra research. It seems that this comes from the interaction between SystemD(`pam_systemd`) and most Wayland environments. And not setting the environment variable could mean that other environments don't work anymore. 

At the moment I am a bit swamped with other things, but I will look into moving this all forward in a couple of weeks.

Thank you again for the issue, I do really appreciate them. If you have any extra insight into the problem, please let me know.

**Comment by coastalwhite** [comment]
This is now fixed in v0.3.1 :smile:
