### ISSUE TITLE
buildtime deps are not specified

### ISSUE THREAD

**Issue by krysopath** [coastalwhite/lemurs#118]
compilation of lemurs failed on raspberry/debian buster minimal issue due to missing dependency to `libpam-dev` during linking with:

```
ld: cannot find -lpam
(...)
```

Installing `libpam0g-dev` via `libpam-dev` fixed all linker errors. 

It would be nice to include the build-deps into the readme/install.sh

**Comment by coastalwhite** [comment]
This was already specified in the `develop` branch. I will do my best to get this branch merged sometime in the near future.
