### ISSUE TITLE
Something wrong with the environment variables / configurations

### ISSUE THREAD

**Issue by golanor** [coastalwhite/lemurs#125]
Hi,

Related to #124, it seems that there is an issue for lemurs to read the correct configuration paths. For i3 I was able to handle it by directly supplying the path to the config file, but now emacs doesn't even look for the emacs directory in $xdg_config_home, but instead creates a new configuration every time at .emacs.d.
This happens to other applications as well - the font configuration is now messed up and I'm not sure how to restore it, and xrandr doesn't work when I try to set it up automatically in the boot screen.
I'm using Arch, and I built lemurs from source and installed it myself (the installation script didn't work, it kept saying that sudo isn't installed).

**Comment by golanor** [comment]
After further investigations - it seems that every time I try to configure something, it creates a `\$HOME/.config` directory at the directory I'm at.

**Comment by coastalwhite** [comment]
I have been wondering where that was coming from. I don't think that is in Lemurs itself but rather upstream somewhere. Will do some investigation.

**Comment by golanor** [comment]
Another issue - unicode stopped working when I run through lemurs. All the locale/language variables are correct

**Comment by golanor** [comment]
> After further investigations - it seems that every time I try to configure something, it creates a `\$HOME/.config` directory at the directory I'm at.

This was due to an error on my end - I had the environment variables configured in /etc/environment.

Another issue - PulseAudio does not detect any soundcard, seems to be related to an issue with permissions. Following ArchWiki, it seems that the XDG session is configured in the wrong manner:
https://wiki.archlinux.org/title/General_troubleshooting#Session_permissions

**Comment by coastalwhite** [comment]
The XDG session issue is fixed on develop. It also fixes many other issues.
