### ISSUE TITLE
X post_login fails if `/bin/sh` is linked to `dash`

### ISSUE THREAD

**Issue by tranzystorek-io** [coastalwhite/lemurs#128]
Logs:
![obraz](https://user-images.githubusercontent.com/5671049/222831820-ae412cc1-9167-4dda-86f0-0891ae92eabf.png)

This line https://github.com/coastalwhite/lemurs/blob/c64f69ccf81b653d9664c412402f32388d976968/src/post_login/mod.rs#L172 seems to be the culprit, as `dash` only supports a short `-l` flag, not `--login`.

**Comment by coastalwhite** [comment]
Yup, many parts coming together. There was something bound to break. I have fixed it and will push a fix to the main branch.
