### ISSUE TITLE
Exiting xmonad does not go back to the login screen

### ISSUE THREAD

**Issue by dovahcrow** [coastalwhite/lemurs#135]
As described by the title, exiting xmonad does not bring me back to the login screen but instead just freezes.

Here's the last piece of the log:
```
[INFO  lemurs::post_login] Starting X11 session
[INFO  lemurs::post_login::x] Start setup of X
[INFO  lemurs::post_login::x] Filling Xauthority file
[INFO  lemurs::env_container] Set environment variable 'XAUTHORITY' to '/home/ubuntu/.Xauthority'
[INFO  lemurs::post_login::x] Run X server
[INFO  lemurs::post_login::x] X server is running
[INFO  lemurs::auth::utmpx] Adding UTMPX record
[INFO  lemurs::auth::utmpx] Added UTMPX record
[INFO  lemurs::env_container] Removing session environment variables
[INFO  lemurs::env_container] Reverting to environment before session
[ERROR lemurs::env_container] Failed to change the working directory back to
[INFO  lemurs] Waiting for environment to terminate
[INFO  lemurs::post_login] Environment's stdout: """
    localuser:root being added to access control list
    """
[INFO  lemurs] Environment terminated. Returning to Lemurs...
[INFO  lemurs::auth::utmpx] Removing UTMPX record
```

here is how I start the xmonad
```bash
# cat /etc/lemurs/wms/xmonad
exec xmonad
```

xmonad is using a minimal configuration:
```haskell
# cat ~/.config/xmonad/xmonad.hs
import XMonad

import XMonad.Util.EZConfig
import XMonad.Util.Ungrab

main :: IO ()
main = xmonad $ def
    { modMask = mod4Mask  -- Rebind Mod to the Super key
    }
```

htop after freezing:
<img width="957" alt="CleanShot 2023-03-21 at 17 10 03@2x" src="https://user-images.githubusercontent.com/998606/226769421-ed8a3f70-a639-49df-b0bb-8baea3e12d3c.png">

System: Archlinux
lemurs: 60fda2abc3743ebedc7d5470f4db2b771b7448a0

**Comment by coastalwhite** [comment]
I have seen this with other Window Managers as well. I have narrowed down the reason. For some reason, `wait_with_output` function does not unblock when the window manager exits for some reason. I am not really sure why, testing with other code seemingly makes it wait. The documentation of the function also doesn't say anything about it.

**Comment by dovahcrow** [comment]
Not sure if related. If I add conky to xmonad, exiting xmonad gives me a new behaviour: xmonad exited but remains Zombie, and conky won't exit, and finally, lemur still waits for xmonad to exit.

**Comment by dovahcrow** [comment]
digging a little bit, https://github.com/rust-lang/rust/blob/master/library/std/src/sys/unix/process/process_unix.rs#L691, from here you can see `wait` also waits for any child process that the wm spawns (0 in libc::waitpid). This might be the reason

**Comment by coastalwhite** [comment]
Thank you very much for that research. I did find the issue. The open pipes prevent from waiting for the process. I think I will patch it so that it logs to a separate log file instead of the lemurs.log. :smile:

**Comment by dovahcrow** [comment]
@coastalwhite I just tested the latest master. Thing worked out perfectly! Thanks for the patch!
