### ISSUE TITLE
Starting X timed out! 

### ISSUE THREAD

**Issue by Elkellympia** [coastalwhite/lemurs#139]
distro: fresh arch install, minimal
wm: awesomewm (runs well if i run xinit awesome)
Initi lemurs just brings me to a black screen, the following logs (if the log rewrites itself) are from following testing after that init lemurs but the logs are the same

here is the lemurs.log output, i could not copy it from my cell phone, sorry about that

http://termbin.com/r3uz

my script /etc/lemurs/wms/awesomewm is just the following

```
#! /bin/sh
exec awesome
```
Just tried changing the script from exec awesome to xinit awesome, just testing
The log is exactly the same

**Comment by coastalwhite** [comment]
It looks like you are running using an NVIDIA card. I have noticed myself that Xorg takes a very long time to load for NVIDIA, maybe it is too long in your case. I will have a look tonight at making this time-out factor scalable from the config. 

Does it also take some time to load with xinit?

**Comment by coastalwhite** [comment]
What we currently have is based on how ly did it, but that implementation is very hacky. I had a look at what xinit is doing and actually that is a way better solution.

I am testing now on VMs and it seems much faster and cleaner, I will test on a pc with an NVIDIA card tomorrow and after that, I will push the fix :smile:

**Comment by coastalwhite** [comment]
Not 100% sure. It may be completely unrelated. I will have a look tomorrow whether this helps on the NVIDIA device.

**Comment by coastalwhite** [comment]
On the NVIDIA device it seems to speed it up by a bit, but nothing too enormous. The patch does improve a lot of the aspects around the X start process, though. Would love for you to try one more time and let me know how that goes.

**Comment by coastalwhite** [comment]
FYI, I also just merged in something where the `stdout` and `stderr` logs of your xinit script go to `/var/log/lemurs.client.log` and the logs of Xorg go to `/var/log/lemurs.xorg.log`.

That should also massively help debugging :smiley:

**Comment by coastalwhite** [comment]
Good to hear.

The cut-off on the name occurs because the environment names are capped to 8 columns. It looks quite weird if the names are not all the same number of columns.  To be honest, this should be configurable.
