### ISSUE TITLE
Ctrl+u not working in inputs (delete/cut)

### ISSUE THREAD

**Issue by xVermillionx** [coastalwhite/lemurs#149]
Normally in the console/shell (and some guis firefox, sway-lock, dconf-editor etc.) it is possible to delete/cut the whole line using Ctrl+u.

This is a feature/shortcut I really miss and think would be a great addition.

**Comment by coastalwhite** [comment]
This is a good idea. I will get started on this. The shortcuts that we should probably port:

- `Ctrl+A`: Go to the beginning
- `Ctrl+E`: Go to end
- `Ctrl+L`: Clear the line
- `Ctrl+U`: Clear everything before the cursor
- `Ctrl+K`: Clear everything after the cursor
- `Ctrl+D`: Same as `Delete`
- `Ctrl+H`: Same as `Backspace`
- `Ctrl+B`: Same as `Left`
- `Ctrl+F`: Same as `Right`
- `Ctrl+P`: Same as `Up`
- `Ctrl+N`: Same as `Down`

The source taken is [this](https://ss64.com/bash/syntax-keyboard.html).

I don't think we should do the word commands, as they create a lot of added complexity.
