### ISSUE TITLE
Massive lemurs.client.log file for compositor error

### ISSUE THREAD

**Issue by ErenKyojin** [coastalwhite/lemurs#160]
For the second time in a few months of usage i've run into this issue now, and that is having an infinite growing `/var/log/lemurs.client.log` file, at the moment is at about 40GBs.

The file as far as i can see is just this message:
`[ 06/24/2023 09:48:49.887 redirect_start FATAL ERROR ] Another composite manager is already running (and does not handle _NET_WM_CM_Sn correctly)`
Logged about 10 times per milliseconds. 

Now the core issue is probabily in my i3 config file or in picom itself since it's the only composite manager i have and i had in fact two instance of picom running and killing the second stopped the file from growing. But i do belive this should not be generating such a massive file in less than 6 hours.

**Comment by coastalwhite** [comment]
Yeah, oops :sweat_smile:. That is clearly not what we want.

If I understand correctly, this is just from one session? As in, if you restart the computer, the file is empty again and starts growing from 0GBs once more?

Anyway, I think I know how to fix this. I will take a look at fixing this soon.

**Comment by ErenKyojin** [comment]
> If I understand correctly, this is just from one session? As in, if you restart the computer, the file is empty again and starts growing from 0GBs once more?

I can't be 100% sure because i noticed only when the disk usage was already at 95+% so i removed the file manually, but if i had to guess i'd say yes since it's very likely it already happened in the past, maybe for shorter sessions, and i did not notice it. Thank you for the quick answer!
