### ISSUE TITLE
Power menu not visible

### ISSUE THREAD

**Issue by vredesbyyrd** [coastalwhite/lemurs#164]
Hello, I feel stupid filing this like I must be missing something...but the power menu (reboot/shutdown) is not visible on my system.  I'm using arch linux with lemurs-git from the aur. 

I'm using a default config, `allow_shutdown` and `allow_reboot` both = `true`. Although the power menu is not visible in the menu, `F1` and `F2` are functional and successfully shutdown/reboot the machine. 

There are no errors in any of the logs. Any thoughts? Thanks for your time!

EDIT: 

`lemurs --preview`

![Screenshot from 2023-06-27 18-12-29](https://github.com/coastalwhite/lemurs/assets/22080838/40263632-2035-431b-b291-216bd9eae464)

**Comment by coastalwhite** [comment]
Ah, no. You are not stupid. It seems there was a regression in an update in the last few days that made the power menu invisible. I will look into it.

**Comment by coastalwhite** [comment]
It was a simple fix. It should now be visible again. Totally my bad.

**Comment by vredesbyyrd** [comment]
Yup, its visible now. And no worries at all, I appreciate the quick fix. Very nice project btw!
