### ISSUE TITLE
Stable AUR Package?

### ISSUE THREAD

**Issue by vladaviedov** [coastalwhite/lemurs#169]
Hi,

Will there be stable & binary packages for AUR?

**Comment by coastalwhite** [comment]
This is planned for the near future, yes. Currently, we are on a bit of a standstill since I am busy elsewhere, but this is happening somewhere.

**Comment by coastalwhite** [comment]
There is now a [stable AUR package](https://aur.archlinux.org/packages/lemurs).

**Comment by vladaviedov** [comment]
> There is now a [stable AUR package](https://aur.archlinux.org/packages/lemurs).

Nice! Although usually binary AUR packages have the -bin suffix I think.
Also the git package should conflict the base one since they own the same files.
