### ISSUE TITLE
Do XDG Common Paths overwrite chosen options?

### ISSUE THREAD

**Issue by thcrt** [coastalwhite/lemurs#170]
I may be completely wrong in my understanding here -- apologies if that's the case.

In `set_xdg_common_paths()`, the environment variables for the XDG Base Directory specification are set:
https://github.com/coastalwhite/lemurs/blob/d8fe49931798dd054d79e17f9fb3371168d800ca/src/post_login/env_variables.rs#L64-L74C2

I suspect this is causing my configuration to be overwritten. I set these variables by `DEFAULT` and by `OVERRIDE` in `/etc/security/pam_env.conf`. I then find that they've been overwritten by the time I load into an environment. Could this be because of these defaults being set? Doesn't the specification as written remove a necessity to explicitly define the variables unless setting them to a non-default value?

Thanks!

**Comment by coastalwhite** [comment]
Ah, that is indeed an issue. Thank you for bringing this to my attention.

I have a fix in mind, but it might take some time until I have time to implement it. Essentially, we define a `remove_var` and a `set_if_unset` in the `EnvironmentContainer`. Before authentication, we can call `remove_var` on all the XDG variables. Then, we replace the `process_env.set` in `set_xdg_common_paths()` with `process_env.set_if_unset`.

**Comment by thcrt** [comment]
Right. I'm not particularly familiar with Rust or the Lemurs codebase, so I don't really understand your proposed fix -- I'll take your word for it, but I don't think I can PR it myself ;)

Unfortunately, this is preventing me using Lemurs for the time being. It's an otherwise great piece of software, though, so thank you for all your work on it, and for your quick response. Whenever you get around to it, let me know and I'll be happy to reinstall! :)

**Comment by coastalwhite** [comment]
Heya!

I got around to addressing this issue. It works for me currently but I would love to know whether this actually resolves the issues you were experiencing. Otherwise, I should reopen the issues.

**Comment by thcrt** [comment]
Woohoo! This will be available from AUR, right? Since it's built from git?

**Comment by coastalwhite** [comment]
Yup, although the cache needs to be cleared before.

**Comment by thcrt** [comment]
Holy shit! It works! My environment variables are now correct. This is brilliant, thank you so much for the fix and the quick support (and of course for the sick display manager). 

Much love <3
