### ISSUE TITLE
Missing 0.3.2 version bump in Cargo.lock file

### ISSUE THREAD

**Issue by tranzystorek-io** [coastalwhite/lemurs#175]
As in title, the bump must have slipped away as it tends to 😛

**Comment by coastalwhite** [comment]
Whoops. Thank you, it is solved now.

**Comment by tranzystorek-io** [comment]
This might warrant a 0.3.3 release with a correct 0.3.3 bump if anyone out there also builds lemurs locked

**Comment by coastalwhite** [comment]
There is no `crates.io` package for lemurs and the `lemurs-git` package uses the `main` branch as a target, but I can retag the release on GitHub.
