### ISSUE TITLE
xsetup when trying to execute my WM manager script (BSPWM), returns permission denied 

### ISSUE THREAD

**Issue by I7sReact** [coastalwhite/lemurs#191]
So, when trying to login, It tries to startx, but after that, It returns to the DM, so i gone to verify the logs inside /var/log/

lemurs.log and lemurs.x11 didnt indicate any problems (only a xkb problem, but It isnt related to the problem)

But in lemurs.client, appeared that xsetup returned permission denied

![IMG_20240110_150549377_HDR.jpg](https://github.com/coastalwhite/lemurs/assets/83084175/0142b961-de03-4968-b68c-01dfeb3ca2c3)

Sorry If this issue isnt very detailed, i dont write a lot of then 

(And yes, the script has permissions to execute, i set It up as 744)

**Comment by coastalwhite** [comment]
> (And yes, the script has permissions to execute, i set It up as 744)

Just to confirm, by this you mean that the `/etc/lemurs/wms/bspwm` is executable? Did you also include a `#! /bin/sh` at the start of the `bspwm` file?

**Comment by I7sReact** [comment]
Both are correct, the `/etc/lemurs/wms/bspwm` is a executable and the file has `#! /bin/sh`

And some extra details i forgot to say

Im using Fedora 39

I was getting a Pam related error too, about not being able to connect to It or something similar, but found a workaround in a past issue of the project, where i edit the `/etc/pam.d/login` file and Change in the pam_loginuid.so line, required to optional

Idk If this can help

**Comment by NotAProgramerLol** [comment]
I had the same issue with awesomeWM , I got it working tho by changing the permissions to 755.

**Comment by I7sReact** [comment]
@NotAProgramerLol Thank you!
