### ISSUE TITLE
Audio/Pipewire doesnt work when doing login via lemurs, but works when doing a manual startx to bspwm

### ISSUE THREAD

**Issue by i7sreact** [coastalwhite/lemurs#192]
Im using Fedora 39
systemd 254.7

After fixing the xsetup problem that was related to permissions, i encountered another problem, but now, with audio/pipewire, where it doesnt work

I did not find anything that indicates the problem in the logs

Tried to add the `exec dbus-launch` and `pipewire` in the launch script, but in the end, it did nothing, since i thought that was a dbus or pipewire launching problem at first

So i gone directly for pipewire and wireplumber, and looks like its modules and files arent being able to load or a unavailable

```
$ pipewire
[E][01591.956256] mod.protocol-native | [module-protocol-:  760 lock_socket()] server 0x561322308b90: unable to lock lockfile '/run/user/1000/pipewire-0.lock': Resource temporarily unavailable (maybe another daemon is running)
[E][01591.956753] pw.conf      | [          conf.c:  573 load_module()] 0x5613222e3500: could not load mandatory module "libpipewire-module-protocol-native": Resource temporarily unavailable
[E][01591.957051] default      | [      pipewire.c:  105 main()] failed to create context: Resource temporarily unavailable
```
```
$ wireplumber
M 14:10:00.368569          wp-device ../lib/wp/device.c:619:wp_spa_device_new_from_spa_factory: SPA handle 'api.libcamera.enum.manager' could not be loaded; is it installed?
M 14:10:00.368601   script/libcamera libcamera.lua:173:chunk: PipeWire's libcamera SPA missing or broken. libcamera not supported.
W 14:10:00.377610                 pw ../spa/plugins/bluez5/upower.c:54:upower_get_percentage_properties_reply: Failed to get percentage from UPower: org.freedesktop.DBus.Error.NameHasNoOwner
W 14:10:00.382941  spa.bluez5.native ../spa/plugins/bluez5/backend-native.c:1840:sco_listen: listen(): Address already in use
W 14:10:00.383089  spa.bluez5.native ../spa/plugins/bluez5/backend-native.c:2393:register_profile_reply: RegisterProfile() failed: org.bluez.Error.NotPermitted
W 14:10:00.383104  spa.bluez5.native ../spa/plugins/bluez5/backend-native.c:2393:register_profile_reply: RegisterProfile() failed: org.bluez.Error.NotPermitted
```

But while using only startx (im not using a .xinitrc, im using only `startx /usr/bin/bspwm`), pipeiwire is loaded normally and i can play audio normally

(And without creating another issue, im having problems were poweroff, reboot, shutdown, ect. They have an output that says that it fails to call the program, since it need an interactive authentication. `Call to PowerOff failed: Interactive authentication required.`)

**Comment by I7sReact** [comment]
Forget both the pipeiwire and wireplumber outputs, i entered now via a manual startx and i saw that even here the output is the same

So idk what it is, idk where to look for to try to help

**Comment by I7sReact** [comment]
Ok, the last part is answeared with the issue #21

Maybe this logind problem can be the cause?
