### ISSUE TITLE
TTY option disappears after configuring river in ``/wayland``

### ISSUE THREAD

**Issue by kardwen** [coastalwhite/lemurs#193]
I added the script ``/etc/lemurs/wayland/river`` and on reboot the TTY option disappeared. I'm not sure if I'm missing something here but it might be nice to keep around by default.

```shell
#! /bin/sh
exec river

```

**Comment by coastalwhite** [comment]
Heya!

The `environment_switcher.include_tty_shell` in the `/etc/config.toml` is set to `false` by default. If you enable that, it will show even if there are graphical environments available.

I hope that helps :smile:
