### ISSUE TITLE
Default `system_shell` value in config.toml causes Lemurs to fail to log in on most distros

### ISSUE THREAD

**Issue by NullCub3** [coastalwhite/lemurs#199]
The value of `system_shell` in the config file is set to `/usr/sh` which is not valid on most* distros from what I've checked. This causes lemurs to give the error "Failed booting into the graphical environment" when trying to log in. In the log it says the reason is "No such file or directory (os error 2)" with no other indication that the error is that the shell is improperly set.

To fix this while also ensuring compatibility with NixOS, the value should be set to `/usr/bin/env sh` or potentially `/bin/sh`.

\* I checked NixOS, Debian 12, and Arch, and none of them had a shell at `/usr/sh`, and I don't think that's a standard place to put the binary anyways. I could be wrong however.

(P.S. Thank you for the amazing program!)

EDIT: I forgot to check if `/usr/bin/env sh` actually works with Lemurs, it apparently doesn't, so that would have to get fixed before it could be used. `/bin/sh` does appear to work with nixos at first glance as well?

**Comment by coastalwhite** [comment]
Oof, yeah that just a mistake. I regard the main branch as mostly unstable, weird that it worked on Arch with those settings then. Well anyway, I will fix it as soon as possible.

btw, can you share your setup for nixos? I was working on a nixos module for lemurs.
