### ISSUE TITLE
Remember Credentials

### ISSUE THREAD

**Issue by kilokon** [coastalwhite/lemurs#39]
Have been using Lemurs for over a few weeks now, appreciate it and plan to not shift back to Ly. 

Suggesting a few features.
- Remember some login credentials
- Resized boxes

**Comment by coastalwhite** [comment]
I think both are good ideas.

How would you imagine the remembering of credentials to work? Would you want to be able to set a default value within the configuration file, or do you just want the last times value to show up?

**Comment by coastalwhite** [comment]
The resized boxes are added references in #40 and fixed in #41

**Comment by coastalwhite** [comment]
The username of the last successfully logged-in user can be remembered in the next version.

I am not sure about the multiple users variant. Is that something you would want? I personally don't really use multiple accounts.
