### ISSUE TITLE
Logout command

### ISSUE THREAD

**Issue by coastalwhite** [coastalwhite/lemurs#50]
Add a logout command. This should probably communicate to the original process to kill the X process.

**Comment by coastalwhite** [comment]
This can be done with Unix sockets:
<http://kmdouglass.github.io/posts/a-simple-unix-socket-listener-in-rust/>

**Comment by coastalwhite** [comment]
This is redundant since we can just use `systemctl restart lemurs`

**Comment by laur89** [comment]
> systemctl restart lemurs

Does this constitute as a session logout?
